# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-iam-chamber-s3-role
  description: Terraform module to provision an IAM role with configurable permissions to access S3 as chamber backend
  homepage: https://cloudposse.com/accelerate
  topics: ""

